[[main]]
  name       = 'Fork!'
  identifier = 'fork'
  weight     = 3
  url        = 'https://github.com/marcostx/marcostx.github.io'
  pre        = 'github'
  [[main.params]]
    target   = '_blank'

[[main]]
  name       = 'Series'
  identifier = 'series'
  pageRef    = '/series'
  weight     = 1

  [[main]]
    name       = 'Academic Journey'
    identifier = 'academic-journey'
    pageRef    = '/post/education-research'
    parent     = 'series'
    Post       = 'Education & Research Background'

  [[main]]
    name       = 'Professional Experience'
    identifier = 'professional-experience'
    pageRef    = '/post/nubank-experience'
    parent     = 'series'
    Post       = 'Current role at Nubank'

    [[main]]
      name       = 'Nubank (Current)'
      identifier = 'nubank-current'
      pageRef    = '/post/nubank-experience'
      parent     = 'professional-experience'
      Post       = 'Senior ML Engineer'

    [[main]]
      name       = 'Raízen'
      identifier = 'raizen-exp'
      pageRef    = '/post/raizen-experience'
      parent     = 'professional-experience'
      Post       = 'ML Engineer & Data Scientist'

    [[main]]
      name       = 'Beegol'
      identifier = 'beegol-exp'
      pageRef    = '/post/beegol-experience'
      parent     = 'professional-experience'
      Post       = 'Data Scientist & ML Engineer'

    [[main]]
      name       = 'Quaasar ML'
      identifier = 'quaasar-exp'
      pageRef    = '/post/quaasar-experience'
      parent     = 'professional-experience'
      Post       = 'Data Scientist'

    [[main]]
      name       = 'Optimale Tecnologia'
      identifier = 'optimale-exp'
      pageRef    = '/post/optimale-experience'
      parent     = 'professional-experience'
      Post       = 'Junior Data Scientist'

    [[main]]
      name       = 'TecSinapse'
      identifier = 'tecsinapse-exp'
      pageRef    = '/post/tecsinapse-experience'
      parent     = 'professional-experience'
      Post       = 'Software Engineer Intern'

    [[main]]
      name       = 'PsG Tecnologia'
      identifier = 'psg-exp'
      pageRef    = '/post/psg-experience'
      parent     = 'professional-experience'
      Post       = 'First Tech Experience'

[[main]]
  name       = 'Works'
  identifier = 'works'
  pageRef    = '/post'
  weight     = 2

  [[main]]
    name       = 'All Posts'
    identifier = 'all-posts'
    pageRef    = '/post'
    parent     = 'works'
    Post       = 'View all articles'
    weight     = 1

[[more]]
  name       = 'About'
  identifier = 'about'
  pageRef    = '/'
  weight     = 5

  [[more]]
  name       = 'Author'
  identifier = 'author'
  pageRef    = '/author'
  parent     = 'about'
  weight     = 2

[[author-name]]
  name       = ''
  identifier = '@user-name'
  pageRef    = '/'
  weight     = 1
  pre        = 'bluesky'

[[author-name]]
  identifier = 'discord'
  pageRef    = '/'
  weight     = 2
  pre        = 'discord'

[[author-name]]
  name       = ''
  identifier = 'mastodon'
  pageRef    = '/'
  weight     = 3
  pre        = 'mastodon'


[[footer]]
  identifier = 'email'
  url        = 'mailto:marcostx1994@gmail.com'
  weight     = 1
  name       = 'email'
  pre        = 'email'

[[footer]]
  identifier = 'linkedin'
  url        = 'http://www.linkedin.com/in/marcos-vinícius-575105a3'
  weight     = 2
  name       = 'linkedin'
  pre        = 'linkedin'
  [[footer.params]]
    target   = '_blank'

[[footer]]
  identifier = 'linktr'
  url        = 'https://linktr.ee/marcos_tex'
  weight     = 3
  name       = 'other links'
  pre        = 'link'
  [[footer.params]]
    target   = '_blank'
