permalink: /:1994:12:09/:Marcos Teixeira
url: "https://marcostx.github.io"
baseurl: /project

# variables
name: Marcos Teixeira
description: Data Scientist & Researcher


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
