url: "https://marcostx.github.io"
baseurl: ""

# variables
name: Marcos Vinícius
description: Senior Machine Learning Engineer | AI Engineer @ Nubank
author: Marcos Vinícius
email: marcostx1994@gmail.com
linkedin: http://www.linkedin.com/in/marcos-vinícius-575105a3
location: São Paulo, São Paulo, Brasil


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
