baseURL = 'https://marcostx.github.io/'
languageCode = 'en-us'
title = 'Marcos Vinícius'
theme = 'hugo-brewm'

[params]
  author = 'Marcos Vinícius'
  description = 'Senior Machine Learning Engineer | AI Engineer @ Nubank'
  email = 'marcostx1994@gmail.com'
  linkedin = 'http://www.linkedin.com/in/marcos-vinícius-575105a3'
  location = 'São Paulo, São Paulo, Brasil'
